"""job

Revision ID: a854abab9938
Revises: 00b5e797f84d
Create Date: 2026-05-07 20:45:02.860721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a854abab9938'
down_revision: Union[str, Sequence[str], None] = '00b5e797f84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_backup_configs', sa.Column('tenant_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_backup_configs', 'tenant_name')
    # ### end Alembic commands ###
